### ISSUE TITLE
Discord Webhook Error

### ISSUE THREAD

**Issue by Rekrap13** [Prince25/StockAlertBot#102]
It sends this after npm start

SyntaxError: Unexpected token h in JSON at position 445
    at JSON.parse (<anonymous>)
    at file:///K:/StockAlertBot/src/main.js:67:10
    at ModuleJob.run (node:internal/modules/esm/module_job:175:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)

I removed the URL from config.json and everything worked. Is there a correct format for the URL. This was the one I inputted : https://discord.com/api/webhooks/X/Y. X/Y are subbed.

**Comment by Prince25** [comment]
Hi. Yeah, this error is most likely due to you writing the URL in a wrong format. You can either use the browser method to do it for you or follow the example below: 
```json
"WEBHOOK_URLS": [
    "https://discord.com/api/webhooks/X/1",
    "https://discord.com/api/webhooks/X/2"
],
```

**Comment by Prince25** [comment]
Closed due to inactivity.
