### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by LightOrithm** [Prince25/StockAlertBot#103]
#npm start                                                                                                                       1 ⨯

> stock-alert-bot@4.0.0 start
> node src/main.js

file:///root/StockAlertBot/src/stores/antonline.js:10
                const title = $(TITLE_SELECTOR).text()?.trim();
                                                       ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
npm ERR! code 1
npm ERR! path /root/StockAlertBot
npm ERR! command failed
npm ERR! command sh -c node src/main.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-18T17_29_07_692Z-debug.log

[
![2021-05-18 18_28_32-Kali Linux 2020 - VMware Workstation 16 Player (Non-commercial use only)](https://user-images.githubusercontent.com/75187305/118698269-1cf50180-b808-11eb-9394-0e7734fd389b.png)
](url)

Platform Information
 - Kali Linux 
 - Node version 12.20.1

**Comment by Prince25** [comment]
Hello there. Please update your Node version to 14.x.x. ([source](https://stackoverflow.com/a/59574160/13915206))
