### ISSUE TITLE
Best Buy Issue

### ISSUE THREAD

**Issue by Reboot-kun** [Prince25/StockAlertBot#107]
Hey Prince,

**Describe the bug**
The bot doesn't seem to work on Best Buy. Other websites seem to work.

![Capture3333](https://user-images.githubusercontent.com/70432237/120093371-c5825a00-c154-11eb-870e-80d306795c4b.PNG)

**Platform Information**
 - OS: Win 10
 - Node version Node  

[bestbuyErrorPage.zip](https://github.com/Prince25/StockAlertBot/files/6565766/bestbuyErrorPage.zip)
[bestbuy.zip](https://github.com/Prince25/StockAlertBot/files/6565767/bestbuy.zip)

v14.16.1.

**Comment by Prince25** [comment]
Hi! It's not failing perse, Best Buy is actually showing a splash screen as you see below.
![image](https://user-images.githubusercontent.com/28243638/120269402-9d7e1e00-c25c-11eb-9885-16299747c9dd.png)

Which country are you located in? Take a look at [this](https://github.com/Prince25/StockAlertBot/issues/30) similar issue.

**Comment by Prince25** [comment]
If you go to [BestBuy.com](https://www.bestbuy.com) on the browser, do you see the same page? If so, try going to [this](https://www.bestbuy.com?intl=nosplash). Do you see it now?

**Comment by Reboot-kun** [comment]
I'm located in south korea rn. For the link, I think it does go straight to the store page

**Comment by Prince25** [comment]
Are you trying to have them ship within the US? 
Try adding `?intl=nosplash` to the end of all Best Buy URLs in StockAlertBot and see if it works for you.

**Comment by Reboot-kun** [comment]
Yes, I'm trying to snag one and get it forwarded to where I live, as local prices are somewhere around 3k-4k usd the last time I checked. Also, the solution worked! Thanks for the great help, I'll make sure to donate if I ever do get one!

**Comment by Prince25** [comment]
Glad to hear it. Best of luck to you!

**Comment by Reboot-kun** [comment]
Thanks!
