### ISSUE TITLE
problem with starting the bot

### ISSUE THREAD

**Issue by philosa** [Prince25/StockAlertBot#110]
I finished editing the config.json and ran the npm start command then I got this:
--> npm init -y
Wrote to /home/runner/UPDATED-StockAlertBot/package.json:

{
  "name": "UPDATED-StockAlertBot",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

--> npm install axios aws-sdk express open chalk twilio node-notifier tmp cors envfile https-proxy-agent moment cheerio random-seed nodemailer random-useragent dotenv node-fetch
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known t
 npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-06-24T05_54_53_551Z-debug.log
exit status 1
   

I used[repl.it](replit.com)  to host the bot, it runs linux.

**Comment by Prince25** [comment]
Hi there. Which version of the bot did you download and how did you download it? What command(s) did you run? 
What is the node version on repl.it?

**Comment by Prince25** [comment]
Close for inactivity.
