### ISSUE TITLE
Email being blocked

### ISSUE THREAD

**Issue by Ariya-Nazari** [Prince25/StockAlertBot#111]
the notification never goes through my gmail because it gets blocked by google. What should I do about that? I also tried copy pasting my webhook from discord instead but i dont recieve any notifications through their either.

**Comment by Prince25** [comment]
Hi! Do you receive any errors from Stock Alert Bot for either email or webhook? How do you know Google blocks the emails?

**Comment by Prince25** [comment]
Close for inactivity.
