### ISSUE TITLE
Error checking Amazon, Walmart URLs

### ISSUE THREAD

**Issue by alif-munim** [Prince25/StockAlertBot#112]
**Describe the bug**

I keep receiving the error below for the following Amazon links, but I'm not sure why:
* https://www.amazon.ca/Graphics-DisplayPort-Axial-tech-Auto-Extreme-Backplate/dp/B08C7L3Z13
* https://www.amazon.ca/EVGA-08G-P5-3767-KR-GeForce-Technology-Backplate/dp/B08L8L9TCZ/
* https://www.amazon.ca/MSI-GeForce-RTX-3070-Architecture/dp/B08KWPDXJZ/
* https://www.amazon.ca/PowerColor-AXRX-5600XT-6GBD6-3DHV2-OC/dp/B089CSRBPD
* https://www.amazon.ca/MSI-GeForce-Tri-Frozr-Architecture-Graphics/dp/B08KWN2LZG/
* https://www.amazon.ca/Graphics-IceStorm-Advanced-Lighting-ZT-A30700E-10P/dp/B08LF32LJ6

Any help or clarification would be much appreciated :)

**Logs and Screenshots**
```
[ERROR] 06:26:28: pm: Error occured for AMAZON while checking url: https://www.amazon.ca/EVGA-08G-P5-3767-KR-GeForce-Technology-Backplate/dp/B08L8L9TCZ/
                      Writing HTML to logs/amazonErrorPage.html.
                      This is usually not a problem but if this error appears frequently, please report the error with the log and html files to GitHub.
```

**Platform Information**
 - OS: Windows 10
 - Node version `node -v`: v14.17.1

**Comment by Prince25** [comment]
Hi there. I can't help much without seeing the files in the logs folder.

**Comment by alif-munim** [comment]
Apologies, here is what I see in the logs folder. 
![image](https://user-images.githubusercontent.com/59207653/124046022-02a16c80-d9df-11eb-8f70-0203ceb6f17f.png)


Here are the contents of the `amazon.txt` file:
```
'Unable to get information'
ITEM_INFO: {
    "url": "https://www.amazon.ca/Graphics-DisplayPort-Axial-tech-Auto-Extreme-Backplate/dp/B08C7L3Z13/",
    "notificationSent": false,
    "shouldSendNotification": false,
    "info": {
        "title": "ASUS ROG Strix AMD Radeon RX 5600 XT TOP Edition Gaming Graphics Card (PCIe 4.0, 6GB GDDR6 Memory, HDMI, DisplayPort, 1080p Gaming, Axial-tech Fan Design, Auto-Extreme, Metal Backplate)",
        "image": "https://images-na.ssl-images-amazon.com/images/I/81eeOfCoSPL._AC_SL1500_.jpg",
        "inventory": false
    },
    "title": "",
    "inventory": false
}
```

**Comment by Prince25** [comment]
Could you upload the html file?

**Comment by alif-munim** [comment]
https://gofile.io/d/tPXsHA

**Comment by alif-munim** [comment]
After taking a look at the error pages myself, it looks like Amazon and Walmart are detecting that the checks are from a bot. I think the issue has to do with the `INTERVAL` and `TIME_BETWEEN_CHECKS` properties in `config.json`, although I have left those to their default settings. 

I've increased the  `INTERVAL` and `TIME_BETWEEN_CHECKS` to 30 seconds and 10 seconds respectively, and I've also turned on proxies. However, I'm still getting these errors:

```
[ERROR] 12:33:18: pm: Error occured for WALMART while checking url: https://www.walmart.ca/en/ip/MSI-GeForce-RTX-3070-Gaming-X-TRIO-Graphics-Card-8GB-GDDR6-PCIe-4-0-Ray-Tracing-VR-Ready-RGB-3xDisplayPort-1x-HDMI-2-1-8K-3X-TORX-Fan-Mytrix-Cable/PRD1Y72CLCFWW29
                      Writing HTML to logs/walmartErrorPage.html.
                      This is usually not a problem but if this error appears frequently, please report the error with the log and html files to GitHub.
```

Not sure what else to try 😕

**Comment by Prince25** [comment]
You're correct in saying that Amazon is blocking traffic. This can due to multiple reasons but most of the time, it's when it receives too many requests from one IP in a short period. What the website does when it detects a bot varies from site to site. It can be simple as requiring a captcha or outright blocking traffic for some time. I'm not sure if you used a proxy or not when that HTML was generated but if you didn't, you can simply fill the captcha and you should be good for a while. If it was a proxy, then it's common. Proxies, especially free ones, are shared among many users who could also be using it for Amazon.

As for Wal-Mart, it looks like the URL you provided was for Canada which has a different layout than the US version. Thus, Wal-Mart Canada is currently not supported.

**Comment by alif-munim** [comment]
That makes sense, thank you for the clarification!
