### ISSUE TITLE
npm run settings doesn't have any settings and doesn't save URLs

### ISSUE THREAD

**Issue by slbailey** [Prince25/StockAlertBot#115]
pi@discordbot:~/StockAlertBot $ npm --version
7.21.0
pi@discordbot:~/StockAlertBot $ node --version
v16.7.0

Followed the instructions... Server starts when I do "npm run settings" -- pages have no content and I cannot save URLs... URLs entered manually in config.json do not show up.

![cap1](https://user-images.githubusercontent.com/141894/130694363-0fc6fd83-6b3a-4572-a3de-74dbbe5295f8.PNG)
![cap2](https://user-images.githubusercontent.com/141894/130694364-76ddcc32-25fa-4755-8b82-3b6819a28a09.PNG)
![cap3](https://user-images.githubusercontent.com/141894/130694366-f7b39c6e-152b-4413-8e88-1906c984c4db.png)

**Comment by Prince25** [comment]
Hello. This can happen if the server is unable to open the `config.json`. You can open DevTools (Chrome) or Developer Tools (Firefox) by pressing F12 and let me know what error has occurred.

**Comment by slbailey** [comment]
Gotcha.  This seems to be due to the fact I’m not running it localhost but instead connecting from my PC to the Rpi on port 3250… Can it be modified to allow connecting via remote IP and not just via localhost?

**Comment by Prince25** [comment]
Yes, quite easily. 
**If** you need to change the port, you can do so here: https://github.com/Prince25/StockAlertBot/blob/05692821a43eb64d4d604e84817baace3e6833a3/server/index.js#L43
Then change the address to open here:
https://github.com/Prince25/StockAlertBot/blob/05692821a43eb64d4d604e84817baace3e6833a3/server/index.js#L108

For the page to read the `config.json` properly, you will need to change the server endpoint here:
https://github.com/Prince25/StockAlertBot/blob/05692821a43eb64d4d604e84817baace3e6833a3/server/index.html#L1362

Duplicate of an older issue #41.

**Comment by slbailey** [comment]
Thanks for the speedy reply.  Looking forward to using this!

**Comment by Prince25** [comment]
You're welcome. I'm planning to make it easier to configure in the future.
