### ISSUE TITLE
Walmart monitoring does not work after Walmart updated its website format

### ISSUE THREAD

**Issue by xmpierce1** [Prince25/StockAlertBot#120]
Walmart added Buy Now and changed the Add to Cart look.. Does not detect products anymore for the store..

URL sample:

https://www.walmart.com/ip/AirTag-Leather-Key-Ring-Wisteria/798472488

**Comment by Prince25** [comment]
Thanks for letting me know. I'll push an update out today.

**Comment by Prince25** [comment]
Fixed in [v4.1](https://github.com/Prince25/StockAlertBot/releases/tag/v4.1) (42f008a).
