### ISSUE TITLE
bestbuy url not working 

### ISSUE THREAD

**Issue by ScOrPi074** [Prince25/StockAlertBot#61]
tried many time bestbuy and newegg url and only newegg working

**Comment by Prince25** [comment]
I'll check if Best Buy works on my end.

**Comment by ScOrPi074** [comment]
i m trying to reach you on discord to show you how the bot is working and its only accepting newegg url ,

**Comment by Prince25** [comment]
I didn't get any friend requests. But apparently Best Buy Canada pages were different so I added support for it in the latest update. Try it out, you can copy over your `config.json`.

**Comment by ScOrPi074** [comment]
how can i procedd with that script sorry again im a complete newbie

**Comment by ScOrPi074** [comment]
![bot1](https://user-images.githubusercontent.com/81469418/112753964-eb9a4b00-8fa7-11eb-9247-a9e742feca36.png)
i add bestbuy usa url and canada and 1 newgg

**Comment by ScOrPi074** [comment]
![bot3 5](https://user-images.githubusercontent.com/81469418/112754749-7597e300-8fab-11eb-987f-599cee2886c7.png)
i install the both version 3.5 and the new one you just sent me i add bestbuy canada and usa nothing showing

**Comment by ScOrPi074** [comment]
![bot3](https://user-images.githubusercontent.com/81469418/112754878-34ec9980-8fac-11eb-8817-18fd320cc724.png)

**Comment by ScOrPi074** [comment]
![amazon error](https://user-images.githubusercontent.com/81469418/112758193-fdd1b480-8fba-11eb-8d8a-c4858fa4480d.png)
i put 20 sec interval and 50 delay between urls sending error :(

**Comment by Prince25** [comment]
I have to admit I didn't test it much but not to fret because Best Buy is working, I just forgot to make it show messages. I'll fix it shortly. As for Amazon, is there a reason you're adding the links with queries like `?smid=ATVPDKIKX0DER&tag=data20-20&aod=1`. Most queries are usually fine but I think `&aod=1` may cause a problem. A url like `https://www.amazon.com/dp/B08L8KC1J7` will work just fine. I'd have to investigate it further. You should for sure use proxies with Amazon, btw.

**Comment by ScOrPi074** [comment]
thx for tje support my friend , i just fix the url as u told me , but i still getting amazon 503 error , and the npm adjusting the interval and delay after the error by itself dont know if is it you who code it that way .
so if i will use proxie for amazon and bestbuy doesnt work on proxies is that mean i cannot put all the url in the same config ????

**Comment by Prince25** [comment]
Yes currently, the Amazon one automatically changes the interval. It's not a good design, I know, but it served my purpose when I wrote the bot just for myself. I'm currently in the process of recoding everything from scratch so things ~~will~~ should work much better. It doesn't matter which country you're in to use proxies. I recommended Webshare before but you can search on your own. Remember that using free proxies on Amazon may not work very well.

You can use Best Buy with no proxies and Amazon with proxies at the same time if you have two copies of the project folder and configure them individually. I will close this issue for now and I wish the best of luck to you! I'd appreciate if you can share and donate so I can stay motivated to continue this project. Thank you!

**Comment by ScOrPi074** [comment]
patience yeah your right and i think im a master now in patience its been 3 month trying to get 1 and only gpu so i can start teach my kid how to mount a pc to mine bitcoin :) i really want him to learn about crypto world at his small age :) ok great thx a lot prince i will donate for sure.
