### ISSUE TITLE
Proxy consuming

### ISSUE THREAD

**Issue by aRealBanana** [Prince25/StockAlertBot#76]
I have been using the bot for a while now and I found out that it consumes a lot of proxies, and I think the reason is that how the bot is implemented by searching for product links instead of product pages which makes much more requests, specially via newegg website.
So am wondering is there a way to make it run on a page search rather than product links?
I still didnt get my RTX 3080 been trying for almost a month now :(.

**Comment by Prince25** [comment]
That might be a good idea so we'll work on adding it in the near future. Just so it's not forgotten, could you post this in the [discussions](https://github.com/Prince25/StockAlertBot/discussions) instead?

Sorry to hear that but you gotta keep at it, buddy. You'll get it!
