### ISSUE TITLE
Bad proxy list setting

### ISSUE THREAD

**Issue by Werner9** [Prince25/StockAlertBot#87]
Hi, I'm using a custom proxy app that uses local proxy like 127.0.0.1:12345. For each local port I can change the proxy ip in the app. So i want to know how can i remove the bad ip from the bot since local ips are always fine.

**Comment by Prince25** [comment]
If you wish to not add blocked proxies to the "bad" list, you can comment out the line `badProxies.add(proxy)` for every store that supports proxies. In Amazon, for example: https://github.com/Prince25/StockAlertBot/blob/eee7f401495f8b6900075b5d57263dfc8bff4bd2/stores/amazon.js#L64

**Comment by Werner9** [comment]
Thanks!

**Comment by Prince25** [comment]
Awesome. Hope it works out for you. Please share and consider donating! 😃
