### ISSUE TITLE
Gamestop parsing issue

### ISSUE THREAD

**Issue by procoder-net** [Prince25/StockAlertBot#89]
2:04:57 PM: Error occured for Gamestop. Written to logs/Gamestop.log
This is usually not a problem but if this error appears frequently, please report the error (and the log) to GitHub.
HTML written for Gamestop to logs/GamestopErrorPage.html. Please report this bug to GitHub and upload this file

https://www.gamestop.com/video-games/playstation-5/consoles/products/playstation-5/11108140.html

**Comment by procoder-net** [comment]
`Error: Request failed with status code 412
    at createError (/Users/i055023/Documents/demo/StockAlertBot/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/i055023/Documents/demo/StockAlertBot/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/i055023/Documents/demo/StockAlertBot/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:467:12)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  config: {
    url: 'https://www.walmart.com/ip/Sony-PlayStation-5-Video-Game-Console/363472942',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2224.3 Safari/537.36'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function (anonymous)],
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'www.walmart.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'www.walmart.com',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 1725,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'GET /ip/Sony-PlayStation-5-Video-Game-Console/363472942 HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2224.3 Safari/537.36\r\n' +
      'Host: www.walmart.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'fifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 5,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/ip/Sony-PlayStation-5-Video-Game-Console/363472942',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 412,
      statusMessage: 'Precondition Failed',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://www.walmart.com/ip/Sony-PlayStation-5-Video-Game-Console/363472942',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'www.walmart.com',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://www.walmart.com/ip/Sony-PlayStation-5-Video-Game-Console/363472942',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  response: {
    status: 412,
    statusText: 'Precondition Failed',
    headers: {
      'accept-ranges': 'bytes',
      'content-length': '396',
      'content-type': 'application/json; charset=UTF-8',
      'x-edgeconnect-midmile-rtt': '2',
      'x-edgeconnect-origin-mex-latency': '112',
      expires: 'Sun, 25 Apr 2021 21:14:10 GMT',
      'cache-control': 'max-age=0, no-cache, no-store',
      pragma: 'no-cache',
      date: 'Sun, 25 Apr 2021 21:14:10 GMT',
      connection: 'close',
      'set-cookie': [Array],
      'cache-status': 'Miss',
      'server-timing': 'cdn-cache; desc=MISS, edge; dur=13, origin; dur=112',
      'origin-ex': '',
      'origin-cc': 'max-age=0, no-cache, no-store'
    },
    config: {
      url: 'https://www.walmart.com/ip/Sony-PlayStation-5-Video-Game-Console/363472942',
      method: 'get',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'GET /ip/Sony-PlayStation-5-Video-Game-Console/363472942 HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2224.3 Safari/537.36\r\n' +
        'Host: www.walmart.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/ip/Sony-PlayStation-5-Video-Game-Console/363472942',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'www.walmart.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: {
      redirectUrl: '/blocked?url=Lw==&uuid=2d784580-a60b-11eb-9af0-4f8097205adc&vid=&g=a',
      appId: 'PXu6b0qd2S',
      jsClientSrc: '/px/PXu6b0qd2S/init.js',
      firstPartyEnabled: true,
      vid: '',
      uuid: '2d784580-a60b-11eb-9af0-4f8097205adc',
      hostUrl: '/px/PXu6b0qd2S/xhr',
      blockScript: '/px/PXu6b0qd2S/captcha/captcha.js?a=c&m=0&u=2d784580-a60b-11eb-9af0-4f8097205adc&v=&g=a'
    }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}`

**Comment by Prince25** [comment]
Hello. These seem to be two different issues. Could you post the `Gamestop.log` and `GamestopErrorPage.html`?

**Comment by procoder-net** [comment]
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Timeout.gamestop [as _onTimeout] (file:///Users/i055023/Documents/demo/StockAlertBot/stores/gamestop.js:78:36)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by procoder-net** [comment]
This link has 3 logs.. Target, walmart, Gamestop https://drive.google.com/drive/folders/1zZfsRXpAGr7sP4_GYrekwX07VHxvoSqz?usp=sharing

**Comment by xmpierce1** [comment]
I got the same error today as well.

**Comment by xmpierce1** [comment]
[Gamestop.log](https://github.com/Prince25/StockAlertBot/files/6396076/Gamestop.log)

**Comment by Prince25** [comment]
Thank you for the logs. The Gamestop error should be fixed in v4.0.
@procoder-net For Target, take a look at this: https://github.com/Prince25/StockAlertBot/discussions/58
For Walmart, look at https://github.com/Prince25/StockAlertBot/discussions/64. It mainly has to do with your interval rate and/or your access to Walmart.

**Comment by Prince25** [comment]
@xmpierce1 @procoder-net v4.0 is now released! Please try it out and report any bugs you find. I haven't tested it much.
Closing this issue as it pertains to older version.

**Comment by xmpierce1** [comment]
Sweet .. excited to try out the  new release !

Sent from my mobile device


On Apr 30, 2021, at 10:12 PM, Prabhjot Singh ***@***.***> wrote:

﻿

@xmpierce1<https://github.com/xmpierce1> @procoder-net<https://github.com/procoder-net> v4.0 is now released! Please try it out and report any bugs you find. I haven't tested it much.
Closing this issue as it pertains to older version.
